import { getRule, rules } from './rules'
import type { CheckReport } from './types'

/**
 * A standalone file an engineer can open with no build step. Tailwind and
 * daisyUI come from a CDN here rather than the app's compiled CSS, so the
 * export stays readable — the markup is the deliverable, not the stylesheet.
 */
export function buildStandaloneHtml(title: string, bodyHtml: string, theme = 'light'): string {
  return `<!doctype html>
<html lang="en" data-theme="${theme}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<link href="https://cdn.jsdelivr.net/npm/daisyui@5/daisyui.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body>
${bodyHtml}
</body>
</html>
`
}

export function buildSpecMarkdown(
  title: string,
  report: CheckReport,
  html: string,
): string {
  const { summary } = report
  const totalComponents = summary.onSystemCount + summary.offSystemCount
  const failedRuleIds = new Set(report.findings.map((f) => f.ruleId))

  const lines: string[] = [
    `# ${title}`,
    '',
    `Generated by Design Conform on ${new Date(report.checkedAt).toLocaleString()}.`,
    '',
    '## Summary',
    '',
    `| | |`,
    `|---|---|`,
    `| Components detected | ${totalComponents} |`,
    `| On-system | ${summary.onSystemCount} |`,
    `| Off-system | ${summary.offSystemCount} |`,
    `| Accessibility errors | ${summary.errors} |`,
    `| Warnings | ${summary.warnings} |`,
    `| Needs manual review | ${summary.reviews} |`,
    `| Rules passed | ${summary.passedRuleIds.length} of ${rules.length} |`,
    '',
    '## Components used',
    '',
  ]

  if (report.onSystem.length === 0) {
    lines.push('_No library components detected._', '')
  } else {
    lines.push('| Component | Uses |', '|---|---|')
    for (const use of report.onSystem) {
      lines.push(`| ${use.componentName} | ${use.instances.length} |`)
    }
    lines.push('')
  }

  lines.push('## Off-system components', '')
  if (report.offSystem.length === 0) {
    lines.push('None. Every component detected is part of the approved library.', '')
  } else {
    for (const drift of report.offSystem) {
      const where = drift.instances
        .map((i) => (i.location ? `line ${i.location.line}` : i.domPath))
        .join(', ')
      lines.push(
        `### ${drift.label} — ${drift.instances.length} instance${drift.instances.length === 1 ? '' : 's'}`,
        '',
        drift.reason,
        '',
        `Locations: ${where}`,
        '',
      )
    }
  }

  lines.push('## Standards', '')
  lines.push('| Rule | Category | Result |', '|---|---|---|')
  for (const rule of rules) {
    const count = report.findings.filter((f) => f.ruleId === rule.id).length
    lines.push(
      `| ${rule.title} | ${rule.category} | ${count === 0 ? 'Pass' : `${count} finding${count === 1 ? '' : 's'}`} |`,
    )
  }
  lines.push('')

  if (failedRuleIds.size > 0) {
    lines.push('## Outstanding findings', '')
    for (const finding of report.findings) {
      const rule = getRule(finding.ruleId)
      const where = finding.location ? `line ${finding.location.line}` : finding.domPath
      lines.push(
        `- **${rule?.title ?? finding.ruleId}** (${finding.severity}, ${where}) — ${finding.message}`,
      )
    }
    lines.push('')
  }

  lines.push(
    '## Notes for implementation',
    '',
    `The exported HTML is ${html.split('\n').length} lines of Tailwind + daisyUI markup with no build step. Component marker classes (\`.btn\`, \`.card\`, and so on) map to the approved library — replace them with your framework's component imports rather than copying the utility classes.`,
    '',
  )

  return lines.join('\n')
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function download(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  // Revoke on the next tick so the click has definitely started the download.
  setTimeout(() => URL.revokeObjectURL(url), 0)
}
